2019-05-15 10:49:01 [scrapy.downloadermiddlewares.robotstxt] ERROR: Error downloading <GET http://bxjg.circ.gov.cn/robots.txt>: Middleware RandomUserAgentMiddleware.process_response must return Response or Request, got <class 'NoneType'>
Traceback (most recent call last):
  File "d:\python37\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "d:\python37\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "d:\python37\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 http://bxjg.circ.gov.cn/robots.txt>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python37\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "d:\python37\lib\site-packages\scrapy\core\downloader\middleware.py", line 56, in process_response
    (six.get_method_self(method).__class__.__name__, type(response))
AssertionError: Middleware RandomUserAgentMiddleware.process_response must return Response or Request, got <class 'NoneType'>
2019-05-15 10:49:01 [scrapy.core.scraper] ERROR: Error downloading <GET http://bxjg.circ.gov.cn/web/site0/tab5240/>
Traceback (most recent call last):
  File "d:\python37\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "d:\python37\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "d:\python37\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 http://bxjg.circ.gov.cn/web/site0/tab5240/>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python37\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "d:\python37\lib\site-packages\scrapy\core\downloader\middleware.py", line 56, in process_response
    (six.get_method_self(method).__class__.__name__, type(response))
AssertionError: Middleware RandomUserAgentMiddleware.process_response must return Response or Request, got <class 'NoneType'>
2019-05-15 11:03:13 [scrapy.downloadermiddlewares.robotstxt] ERROR: Error downloading <GET http://bxjg.circ.gov.cn/robots.txt>: Middleware RandomUserAgentMiddleware.process_response must return Response or Request, got <class 'NoneType'>
Traceback (most recent call last):
  File "d:\python37\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "d:\python37\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "d:\python37\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 http://bxjg.circ.gov.cn/robots.txt>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python37\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "d:\python37\lib\site-packages\scrapy\core\downloader\middleware.py", line 56, in process_response
    (six.get_method_self(method).__class__.__name__, type(response))
AssertionError: Middleware RandomUserAgentMiddleware.process_response must return Response or Request, got <class 'NoneType'>
2019-05-15 11:03:13 [scrapy.core.scraper] ERROR: Error downloading <GET http://bxjg.circ.gov.cn/web/site0/tab5240/>
Traceback (most recent call last):
  File "d:\python37\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "d:\python37\lib\site-packages\scrapy\core\downloader\middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "d:\python37\lib\site-packages\twisted\internet\defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: <200 http://bxjg.circ.gov.cn/web/site0/tab5240/>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python37\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "d:\python37\lib\site-packages\scrapy\core\downloader\middleware.py", line 56, in process_response
    (six.get_method_self(method).__class__.__name__, type(response))
AssertionError: Middleware RandomUserAgentMiddleware.process_response must return Response or Request, got <class 'NoneType'>
2019-05-15 11:03:32 [twisted] CRITICAL: Unhandled error in Deferred:
2019-05-15 11:03:32 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "d:\python37\lib\site-packages\scrapy\utils\misc.py", line 47, in load_object
    obj = getattr(mod, name)
AttributeError: module 'circ.middlewares' has no attribute 'RandomUserAgentMiddleware'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python37\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "d:\python37\lib\site-packages\scrapy\crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "d:\python37\lib\site-packages\scrapy\crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "d:\python37\lib\site-packages\scrapy\core\engine.py", line 69, in __init__
    self.downloader = downloader_cls(crawler)
  File "d:\python37\lib\site-packages\scrapy\core\downloader\__init__.py", line 88, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "d:\python37\lib\site-packages\scrapy\middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "d:\python37\lib\site-packages\scrapy\middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "d:\python37\lib\site-packages\scrapy\utils\misc.py", line 49, in load_object
    raise NameError("Module '%s' doesn't define any object named '%s'" % (module, name))
NameError: Module 'circ.middlewares' doesn't define any object named 'RandomUserAgentMiddleware'
